### PR TITLE
Upgrade dependency versions and add Stack files

### PR DESCRIPTION
**Pull request by zimurgh**
I've added Stack files to the repo as well as brought the dependencies up to date. Since the package was last updated, the Applicative Monad proposal has become a reality - making Applicative a superclass of Monad. I've made the albeit small modifications needed to suppress errors and warnings in light of this change.

### CODE REVIEW

**Comment by mitar** [comment]
Hm, you removed dependency versions because they are not needed anymore?

**Comment by mitar** [comment]
Does this also address #2?

And thanks for the contribution!

**Comment by zimurgh** [comment]
> Does this also address #2?

Yes it does, in fact! I actually got that exact same error, which prompted this PR in the first place. Up until last year, you could define a data type to be a Monad without it also having to define it to be an Applicative. The NXT data type is an example of this past fact. They've since corrected the type system such that anything that's a Monad is also an Applicative automatically, so you can just throw in Applicative in among the derived instances so that GHC will stop screaming at you.

There's also an added bonus that you don't have to import both Control.Monad and Control.Applicative in the same module anymore. If you've already imported Control.Monad, Control.Applicative is redundant and can be removed.

> Hm, you removed dependency versions because they are not needed anymore?

Hm, I did that instinctively because 1) I was upgrading practically everything and 2) the new `stack` tool is much better at resolving dependency versions than cabal and it can pretty much do it automatically for you as what package versions it downloads are more or less set in stone based on the current snapshot the [Stackage](https://www.stackage.org/) repository is on (it's currently set to lts-5.3).

If you want, I could try pinning them down to explicit version bounds again if it will make it play nice with cabal. I don't use cabal anymore so I'm not sure if it matters.

**Comment by mitar** [comment]
>  the new stack tool is much better at resolving dependency versions than cabal

So instead of concrete package versions, you depend on a particular version of stackage.

Will this work on [Hackage](https://hackage.haskell.org/package/NXT)? Does it support stack?

**Comment by zimurgh** [comment]
> So instead of concrete package versions, you depend on a particular version of stackage.

Yes, you can still put in concrete package versions in the cabal file (many still do), but each version of Stackage has its own concrete versions for packages. So it's more a matter of "Does this project build and run with this version of Stackage?" And if the answer is yes, then you can just stick to that version of Stackage for all additional dependencies you might later add.

> Will this work on Hackage? Does it support stack?

`stack` only pulls from Hackage when you're using a package that's not currently in Stackage. Less popular/specialist packages that are only on Hackage can be added in under `extra-deps` in the `stack.yaml` file along with the specific version of the package you want retrieved. So `stack` primarily interfaces with Stackage except when a given package hasn't been added to Stackage yet, in which case you'll need to specify a version of the package on Hackage and stack will go there to retrieve it. Basically it's like an official/stable repo vs. community repo kind of thing. And `stack`'s "official" repo is Stackage.

**Comment by mitar** [comment]
No, I meant. Does Hackage support Stack. If we remove versions from the package, will Hackage still be able to handle the package, build documentation, things like that?

**Comment by zimurgh** [comment]
It probably does, but I'm adding the bounds back in since there's no harm. It should build fine for both cabal via Hackage and stack via Stackage.

**Comment by mitar** [comment]
OK, I agree. Thanks!

**Pull request merged**
